#!/bin/bash 

dist=`awk '{print $1 " " $2}' /etc/issue`

tput setaf 3
banner(){
figlet -c Welcome to AI installer Script | lolcat
}

declare -x FRAME
declare -x FRAME_INTERVAL

function icon() {
      FRAME=("⠋" "⠙" "⠹" "⠸" "⠼" "⠴" "⠦" "⠧" "⠇" "⠏")
      FRAME_INTERVAL=0.1
	  local step=0

	  while [ "$step" -lt "${#CMDS[@]}" ]; do
		${CMDS[$step]} & pid=$!

		while ps -p $pid &>/dev/null; do
		  echo -ne "\\r[   ] ${STEPS[$step]} ..."

		  for k in "${!FRAME[@]}"; do
		    echo -ne "\\r[ ${FRAME[k]} ]"
		    sleep $FRAME_INTERVAL
		  done
		done

		echo -ne "\\r[ ✔ ] ${STEPS[$step]}\\n"
		step=$((step + 1))
	  done

}

banner
STEPS='Checking youre system'
CMDS='sleep 2'
icon
hostnamectl

echo ""
if [[ -f /usr/bin/gpt ]]; then
    echo "AI is already installed in $dist"
    exit
fi

STEPS='Installing AI'
CMDS='sleep 2'
read -p  "This script is about to install AI in Youre $dist System, Do you want to continue ? " a
case ${a:0:1} in
    y|Y )
        echo "Continue to install AI in $dist"
        icon
        curl -fsSL https://ollama.com/install.sh | sh
    ;;
    * )
        #echo No
        exit 
        tput sgr0
    ;;
esac

STEPS='Downloads Models'
CMDS='sleep 2'
echo "This progress is to downloads AI models, and it takes 4,7GB of youre HDD"
read -p  "Do you want to continue ? " answer
case ${answer:0:1} in
    y|Y )
        echo "Contiune to downloads models"
        icon
        ollama pull llama3:8b
    ;;
    * )
        #echo No
        exit 
        tput sgr0
    ;;
esac

STEPS='Creating gpt file'
CMDS='sleep 2'
icon
cat << EOF > $PWD/c
#!/bin/bash
ollama run llama3
EOF
sudo mv $PWD/c /usr/bin/gpt
sudo chmod +x /usr/bin/gpt

STEPS='Runnings GPT with llama3'
CMDS='sleep 2'
echo "This will Execute GPT file to test,in next time just type [ gpt ] in youre terminal and type the questions, ctrl + D, /bye,or type exit to exit from AI"
read -p  "Do you want to continue ? " ans
case ${ans:0:1} in
    y|Y )
        echo Contiune to run it 
        gpt
    ;;
    * )
        #echo No
        exit 
        tput sgr0
    ;;
esac
