#!/bin/bash

## Export environment
## ------------------
export PYTHONWARNINGS=ignore

### Update & Upgrade the system
apt update && apt upgrade -y

### add compression level to initramfs
cat <<EOF>> /etc/initramfs-tools/initramfs.conf
COMPRESSLEVEL=19
EOF

##add schemas(ubuntu/debian)
touch /usr/share/glib-2.0/schemas/99_Debian-settings.gschema.override

cat << EOF >> /usr/share/glib-2.0/schemas/99_ubuntu-settings.gschema.override
[org.gnome.shell]
favorite-apps=['google-chrome.desktop', 'org.gnome.Terminal.desktop', 'nemo.desktop', 'org.gnome.Software.desktop', 'arduino.desktop', 'EASYEDA.desktop', 'code.desktop']

enabled-extensions=['arcmenu@arcmenu.com', 'compiz-windows-effect@hermes83.github.com', 'desktop-cube@schneegans.github.com','dash-to-dock@micxgx.gmail.com', 'pop-shell@system76.com']

[org.gnome.desktop.background]
picture-uri = 'file:///usr/share/backgrounds/wallpaper.png'
picture-uri-dark = 'file:///usr/share/backgrounds/wallpaper.png'

[org.gnome.desktop.screensaver]
picture-uri = 'file:///usr/share/backgrounds/wallpaper.png'

[org.gnome.desktop.interface]
color-scheme='prefer-dark'
gtk-theme = "Adwaita-dark"
icon-theme = "McMojave-circle-dark"
cursor-theme = "Qogir"
document-font-name='JetBrainsMono Nerd Font 11'
font-antialiasing='rgba'
font-hinting='slight'
font-name='JetBrainsMono Nerd Font 11'
monospace-font-name='JetBrainsMonoNL Nerd Font 11'
toolkit-accessibility=false

[org.gnome.desktop.wm.preferences]
button-layout='appmenu:minimize,maximize,close'
titlebar-font='JetBrainsMono Nerd Font Medium 11'

[org.gnome.Terminal.Legacy.Settings]
theme-variant = 'dark'

[org.gnome.shell.extensions.dash-to-dock]
disable-overview-on-startup=true
show-mounts-only-mounted=false
show-mounts-network=true
dock-position='BOTTOM'
dock-fixed=true
custom-theme-shrink=true
dash-max-icon-size=32
intellihide-mode='ALL_WINDOWS'
intellihide=true
icon-size-fixed=true
custom-theme-shrink=true
running-indicator-style='DOTS'
extend-height=false
scroll-action='switch-workspace'
click-action='focus-or-previews'
shift-click-action='launch'
middle-click-action='launch'
transparency-mode='FIXED'
shift-middle-click-action='minimize'
background-opacity=0.5
custom-background-color=false
dash-max-icon-size=32
dock-position='BOTTOM'
height-fraction=0.90000000000000002
show-apps-at-top=true
transparency-mode='FIXED'

[shell/extensions/arcmenu]
arc-menu-icon=28
menu-background-color='rgba(48,48,49,0.98)'
menu-border-color='rgb(60,60,60)'
menu-button-appearance='Icon'
menu-button-icon='Menu_Icon'
menu-foreground-color='rgb(223,223,223)'
menu-item-active-bg-color='rgb(25,98,163)'
menu-item-active-fg-color='rgb(255,255,255)'
menu-item-hover-bg-color='rgb(21,83,158)'
menu-item-hover-fg-color='rgb(255,255,255)'
menu-layout='Mint'
menu-separator-color='rgba(255,255,255,0.1)'
prefs-visible-page=0
search-entry-border-radius=(true, 25)
EOF

## Remove `zsys`
## -------------
apt -y purge --auto-remove zsys >/dev/null 2>&1

## Disable error reporting
## -----------------------
sed -i "s/enabled=1/enabled=0/" /etc/default/apport

## Install flatpak
## -----------------------
apt install -y flatpak gnome-software-plugin-flatpak
## add flatpak repo
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

### adding zram-tool
apt install zram-tools && echo -e "ALGO=zstd\nPERCENT=65" | sudo tee -a /etc/default/zramswap && systemctl reload zramswap.service

### installing default apps
apt install -y curl wget git conky nemo neofetch python3 python3-pip python3-venv gnome-shell-extensions gnome-tweaks chrome-gnome-shell gnome-extensions-manager gnome-user-share gnome-nettool node-typescript make gnome-shell-extension-prefs

########### Install starship ##########################
curl -sS https://starship.rs/install.sh | sh
wget -P /usr/share/fonts/JetBrainsMono https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip && cd /usr/share/fonts/JetBrainsMono/ && unzip JetBrainsMono.zip && rm JetBrainsMono.zip && fc-cache -fv
cd
wget https://raw.githubusercontent.com/Kecubunk/mybash/main/config.txt
cat config.txt >> ~/.bashrc
cat config.txt >> /etc/skel/.bashrc
mkdir /etc/skel/.config/
wget -P /etc/skel/.config/ https://raw.githubusercontent.com/Kecubunk/mybash/main/starship.toml
wget -P ~/.config/ https://raw.githubusercontent.com/Kecubunk/mybash/main/starship.toml
rm -f config.txt

## remove gnome-games
## ------------------
apt purge gnome-2048 aisleriot atomix gnome-chess five-or-more hitori iagno gnome-klotski lightsoff gnome-mahjongg gnome-mines gnome-nibbles quadrapassel four-in-a-row gnome-robots gnome-sudoku swell-foop tali gnome-taquin gnome-tetravex -y & apt autoremove -y

## Remove unused apps
## --------------------
apt purge --autoremove -y libreoffice* gnome-text-editor* xterm thunderbird* xiterm+thai* mlterm* mozc* shotwell* Rhythmbox* anthy* goldendict* hdate-applet* debian-faq*  debian-reference* firefox-esr*  yelp* gnome-logs* gnome-characters* evolution* xterm* nautilus

## add extensions
## -------------------
tput setaf 3
echo "Installing gnome-extensions"
tput sgr0

e 307 43  #dashtodock
e 3210 43 #compiz lamp
e 4648 43 #desktop cube
e 5156 43 #desktop clock
e 3628 43 #arc menu

## Compile Schemas
## -----------------
glib-compile-schemas /usr/share/glib-2.0/schemas/

## Keep system safe
## --------
apt purge --autoremove -y libreoffice* gnome-text-editor* xterm thunderbird* transmmision-gtk* xiterm+thai* mlterm* mozc* shotwell* Rhythmbox* anthy* goldendict* hdate-applet* debian-faq*  debian-reference* firefox-esr* nautilus* yelp* gnome-logs* gnome-characters* gnome-fonts-viewer* evolution* 


apt -y update
apt -y remove && apt -y autoremove
apt -y clean && apt -y autoclean

#update initramfs
#update-initramfs -u

# Remove history
rm -f ~/.bash_history
rm -f /root/.bash_history



